xset r rate 300 50
xsetroot -cursor_name left_ptr
setxkbmap -option caps:escape
setxkbmap -layout se,ar -option grp:alt_shift_toggle

dunst &
battlow &
parcellite &

wallpaper &
while xsetroot -name "$(panel)"; do
	sleep 1
done &

while true; do
    dwm
done
