xset r rate 300 50
setxkbmap -layout se,ara -option grp:alt_space_toggle
xsetroot -cursor_name left_ptr
setxkbmap -option caps:escape

dunst &
battlow &
parcellite &

wallpaper &
while xsetroot -name "$(panel)"; do
	sleep 1
done &

while true; do
    dwm
done
